-- Migra users.id de UUID a BIGINT y conserva las tareas si ya existen.
-- Ejecutar una sola vez si users.id todavía es UUID.
begin;

do $$
begin
  if to_regclass('public.tasks') is not null then
    alter table public.tasks
      drop constraint if exists tasks_user_id_fkey;
  end if;
end $$;

alter table public.users
  rename column id to legacy_uuid_id;

alter table public.users
  drop constraint users_pkey;

alter table public.users
  add column id bigint;

with numbered_users as (
  select legacy_uuid_id, row_number() over (order by created_at, legacy_uuid_id) as new_id
  from public.users
)
update public.users as users
set id = numbered_users.new_id
from numbered_users
where users.legacy_uuid_id = numbered_users.legacy_uuid_id;

alter table public.users
  alter column id set not null;

alter table public.users
  alter column id add generated by default as identity;

alter table public.users
  add constraint users_pkey primary key (id);

select setval(
  pg_get_serial_sequence('public.users', 'id'),
  coalesce(max(id), 1),
  max(id) is not null
)
from public.users;

do $$
begin
  if to_regclass('public.tasks') is not null then
    alter table public.tasks
      add column user_id_new bigint;

    update public.tasks as task
    set user_id_new = users.id
    from public.users as users
    where users.legacy_uuid_id = task.user_id;

    alter table public.tasks
      alter column user_id_new set not null;

    alter table public.tasks
      drop column user_id;

    alter table public.tasks
      rename column user_id_new to user_id;

    alter table public.tasks
      add constraint tasks_user_id_fkey
      foreign key (user_id) references public.users(id) on delete cascade;
  end if;
end $$;

alter table public.users
  drop column legacy_uuid_id;

create table if not exists public.tasks (
  id          uuid primary key default gen_random_uuid(),
  user_id     bigint not null references public.users(id) on delete cascade,
  title       text not null check (char_length(title) between 1 and 120),
  description text check (description is null or char_length(description) <= 1000),
  due_date    timestamptz,
  status      text not null default 'pending'
              check (status in ('pending', 'in_progress', 'completed')),
  created_at  timestamptz not null default now()
);

create index if not exists tasks_user_id_due_date_idx
  on public.tasks (user_id, due_date);

alter table public.tasks enable row level security;

commit;
