-- Reasigna users.id desde 1 y conserva la relación de cada tarea con su usuario.
-- Ejecutar una sola vez con el backend detenido y después de la migración 001,
-- si la tabla ya tiene IDs numéricos grandes que se quieren compactar.
begin;

create temporary table user_id_mapping on commit drop as
select
  id as old_id,
  row_number() over (order by created_at, id)::bigint as new_id
from public.users;

do $$
begin
  if to_regclass('public.tasks') is not null then
    alter table public.tasks
      drop constraint if exists tasks_user_id_fkey;
  end if;
end $$;

alter table public.users
  add column id_new bigint;

update public.users as users
set id_new = mapping.new_id
from user_id_mapping as mapping
where users.id = mapping.old_id;

alter table public.users
  alter column id_new set not null;

do $$
begin
  if to_regclass('public.tasks') is not null then
    alter table public.tasks
      add column user_id_new bigint;

    update public.tasks as tasks
    set user_id_new = mapping.new_id
    from user_id_mapping as mapping
    where tasks.user_id = mapping.old_id;

    alter table public.tasks
      alter column user_id_new set not null;

    alter table public.tasks
      drop column user_id;

    alter table public.tasks
      rename column user_id_new to user_id;
  end if;
end $$;

alter table public.users
  drop constraint users_pkey;

alter table public.users
  drop column id;

alter table public.users
  rename column id_new to id;

alter table public.users
  alter column id set not null;

alter table public.users
  alter column id add generated by default as identity;

alter table public.users
  add constraint users_pkey primary key (id);

select setval(
  pg_get_serial_sequence('public.users', 'id'),
  coalesce(max(id), 1),
  max(id) is not null
)
from public.users;

do $$
begin
  if to_regclass('public.tasks') is not null then
    alter table public.tasks
      add constraint tasks_user_id_fkey
      foreign key (user_id) references public.users(id) on delete cascade;
  end if;
end $$;

create table if not exists public.tasks (
  id          uuid primary key default gen_random_uuid(),
  user_id     bigint not null references public.users(id) on delete cascade,
  title       text not null check (char_length(title) between 1 and 120),
  description text check (description is null or char_length(description) <= 1000),
  due_date    timestamptz,
  status      text not null default 'pending'
              check (status in ('pending', 'in_progress', 'completed')),
  created_at  timestamptz not null default now()
);

create index if not exists tasks_user_id_due_date_idx
  on public.tasks (user_id, due_date);

alter table public.tasks enable row level security;

commit;
