-- Añade chats y participantes a una base existente con users.id numérico.
begin;

create table if not exists public.chats (
  id         bigint generated by default as identity primary key,
  name       text not null check (char_length(name) between 1 and 100),
  creator_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_members (
  chat_id   bigint not null references public.chats(id) on delete cascade,
  user_id   bigint not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (chat_id, user_id)
);

create index if not exists chat_members_user_id_idx
  on public.chat_members (user_id);

alter table public.chats enable row level security;
alter table public.chat_members enable row level security;

commit;
