-- Ejecutar en Supabase: SQL Editor > New query
create extension if not exists "pgcrypto";

create table if not exists public.users (
  id            bigint generated by default as identity primary key,
  name          text not null,
  email         text not null unique,
  password_hash text not null,
  created_at    timestamptz not null default now()
);

-- Sin políticas: solo el backend (service role) puede leer/escribir
alter table public.users enable row level security;

create table if not exists public.tasks (
  id          uuid primary key default gen_random_uuid(),
  user_id     bigint not null references public.users(id) on delete cascade,
  title       text not null check (char_length(title) between 1 and 120),
  description text check (description is null or char_length(description) <= 1000),
  due_date    timestamptz,
  status      text not null default 'pending'
              check (status in ('pending', 'in_progress', 'completed')),
  created_at  timestamptz not null default now()
);

create index if not exists tasks_user_id_due_date_idx
  on public.tasks (user_id, due_date);

-- Sin políticas: solo el backend (service role) puede leer/escribir
alter table public.tasks enable row level security;
